### ISSUE TITLE
JSON body in request not supported 

### ISSUE THREAD

**Issue by ap00rv** [insp3ctre/race-the-web#1]
Hi ,
        I was trying to send JSON payload in the body. It gave me parsing error. Is this feature supported ?

**Comment by insp3ctre** [comment]
It should work. However you'll just have to be careful with how you format the data in the request. Specifically, try to not repeat double quotes ("), as the TOML format interprets that as a part of the payload, and will cut off the string after that. It's similar to how you would format quotes inside of string variables in most other languages. Try to use single quotes only inside of the "body" value for a target. Or if you must use double quotes in the payload, enclose the payload with single quotes (making sure to not use single quotes anywhere else in the payload in this case).
