### ISSUE TITLE
Duplicate Content-Type headers on POST request

### ISSUE THREAD

**Issue by cujanovic** [insp3ctre/race-the-web#2]
Hi,
I assume that due to: https://github.com/insp3ctre/race-the-web/blob/master/racer.go#L324

when sending a POST request to some app with Content-Type:application/json header in the toml file, the app receives duplicate Content-Type headers which results with Error 400 Bad Request responses on some apps.

Can this be improved maybe by checking if Content-Type:application/json header is already set and then don't add automatically the Content-Type: application/x-www-form-urlencoded one?

Btw, thanks for making this practical tool!

**Comment by MrVaughan** [comment]
I literally saw the same issue just this minute also. 

If the content type were provided as a header in the config file can that override the one set by the application?

**Comment by insp3ctre** [comment]
Thanks for pointing this out. I can look into writing this in. I'll likely do what @MrVaughan suggested and add in a section for content-type header, defaulting to `application/x-www-form-urlencoded one`.

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by insp3ctre** [comment]
All set. I just did a check for the "Content-Type" header passed in via the config, then added it if it was not already present. Otherwise, it leaves it alone. Thanks for posting this bug!

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))

**Comment by insp3ctre** [comment]
Binaries have been added for [release 2.0.1](https://github.com/insp3ctre/race-the-web/releases/tag/2.0.1), which fixed this issue.

Cheers,
Aaron ([insp3ctre](https://twitter.com/insp3ctre))
